In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import *
from sklearn import cross_validation
from sklearn.preprocessing import MinMaxScaler

In [62]:
data = read_csv("/Users/mrigank/Desktop/python_projects/ML_project/letter-recognition.data.csv", sep=',', header=None)
data
data = np.array(data, dtype=object)
# seperate out X and y
X = data[:,1:]
y = data[:,0:1]
print("size of X is:", X.shape, "size of y is:", y.shape)


size of X is: (20000, 16) size of y is: (20000, 1)


In [63]:
#X -= np.mean(X, axis = 0) # zero-center the data (important)
#X /= np.max(X, axis = 0)
#X = np.array(X, dtype=float)
#X = np.around(X, decimals=2)
X

array([[2, 8, 3, ..., 8, 0, 8],
       [5, 12, 3, ..., 8, 4, 10],
       [4, 11, 6, ..., 7, 3, 9],
       ..., 
       [6, 9, 6, ..., 12, 2, 4],
       [2, 3, 4, ..., 9, 5, 8],
       [4, 9, 6, ..., 7, 2, 8]], dtype=object)

In [64]:
## y labels are formatted into a array of 26 binary numbers, for 26 different classes
y_new = np.zeros(shape = (y.shape))
u = np.unique(y)

for i in range(len(y)):
    for j in range(len(u)):
        if (y[i] == u[j]):
            y_new[i]=j
            break

In [65]:
y_new = np.around(y_new, decimals=0)


In [66]:
np.unique(y)

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'], dtype=object)

In [67]:
np.unique(y_new)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.])

In [68]:
X = X[100:110,:]
y_new = y_new[100:110,:]
print("size of X is:", X.shape, "size of y is:", y_new.shape)

size of X is: (10, 16) size of y is: (10, 1)


In [69]:
X

array([[2, 7, 3, 5, 1, 6, 10, 0, 3, 7, 11, 8, 1, 11, 0, 8],
       [6, 8, 7, 6, 4, 6, 9, 4, 8, 11, 7, 6, 2, 8, 5, 5],
       [5, 9, 6, 7, 5, 7, 7, 7, 5, 7, 6, 7, 2, 8, 9, 8],
       [2, 3, 2, 2, 1, 7, 11, 2, 6, 7, 10, 8, 1, 11, 1, 7],
       [2, 3, 3, 2, 1, 4, 7, 4, 6, 10, 9, 13, 1, 9, 2, 7],
       [4, 10, 7, 7, 2, 9, 8, 5, 3, 5, 14, 8, 3, 9, 0, 8],
       [5, 8, 5, 6, 3, 6, 12, 4, 7, 12, 9, 4, 2, 12, 2, 4],
       [7, 12, 6, 6, 3, 7, 8, 2, 7, 9, 7, 8, 5, 8, 3, 7],
       [3, 8, 4, 6, 4, 7, 8, 7, 6, 7, 7, 5, 3, 8, 3, 7],
       [2, 1, 3, 1, 1, 7, 8, 4, 0, 7, 8, 8, 6, 10, 0, 8]], dtype=object)

In [70]:
y_new

array([[ 24.],
       [ 18.],
       [ 18.],
       [ 19.],
       [  2.],
       [ 21.],
       [ 19.],
       [ 10.],
       [  3.],
       [ 22.]])

In [9]:
# 25% of the data is kept apart for cross-validation and testing
## sklearn function is used to do so
X_train, X_t_cv, y_train, y_t_cv = cross_validation.train_test_split(X, y_new, test_size=0.25)
# data seperated for test & cross-validation
X_cv, X_test, y_cv, y_test = cross_validation.train_test_split(X_t_cv, y_t_cv, test_size=0.5)
X_train.shape, y_train.shape
# train: 15000 : cv: 2500 : test: 2500 observations

((75, 16), (75, 1))

In [71]:
#N = 100  # number of points per class
D = 16  # dimensionality
K = 26  # number of classes

In [79]:
# initialize parameters randomly
h = 32  # size of hidden layer
W = 0.001 * np.random.randn(D, h)
b = np.zeros((1, h))
W2 = 0.001 * np.random.randn(h, K)
b2 = np.zeros((1, K))

In [80]:
# some hyperparameters
step_size = 0.1
reg = 0 #1e-3  # regularization strength

In [81]:
hidden_layer = np.maximum(0, np.dot(X, W) + b)  # note, ReLU activation
scores = np.dot(hidden_layer, W2) + b2
scores

array([[9.383955545032568e-05, -0.0001273405152461553,
        0.00029515226647681893, 8.719039211382394e-07,
        -8.51549410929569e-05, 9.590035506235171e-05,
        9.817413553590742e-05, 3.580575593238504e-05,
        -0.00017967859044820352, 1.1090553017090069e-06,
        -0.0001186814518851819, 5.6781173473443574e-05,
        0.00021667476377241492, 1.8591838768487e-05,
        -0.0001179869151891392, 4.29961213964558e-05,
        5.312308055627674e-05, 5.9071909940405364e-05,
        -8.800111217968191e-05, 1.149880030217374e-05,
        -1.0953723754900007e-05, 2.29008351397889e-06,
        -2.3476393389277198e-05, 0.0001083527952433666,
        -2.7274749588429454e-05, 9.298198306149839e-05],
       [8.593176515828303e-05, -0.00010774913064537267,
        0.0002753969319522033, -6.050101421110496e-05,
        -0.0001493269143637987, 5.597864433680068e-05,
        0.00018576440612763908, 5.681642078511911e-05,
        -0.00017095292172363032, 2.559906462557818e-05,
       

In [82]:
# gradient descent loop
num_examples = X.shape[0]
np.seterr(all='raise')
for i in range(10000):

    # evaluate class scores, [N x K]
    hidden_layer = np.maximum(0, np.dot(X, W) + b)  # note, ReLU activation
    scores = np.dot(hidden_layer, W2) + b2

    # compute the class probabilities
    print("i:", i)
    #print(scores[2,3])
    exp_scores = np.exp(np.float64(scores))
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)  # [N x K]

    # compute the loss: average cross-entropy loss and regularization
    corect_logprobs = -np.log(probs[range(num_examples), y_new.astype(int)])
    data_loss = np.sum(corect_logprobs) / num_examples
    reg_loss = 0.5 * reg * np.sum(W * W) + 0.5 * reg * np.sum(W2 * W2)
    loss = data_loss + reg_loss
    if i % 1000 == 0:
        print("iteration:", i, "loss: ", loss)

    # compute the gradient on scores
    dscores = probs
    dscores[range(num_examples), y_new.astype(int)] -= 1
    dscores /= num_examples

    # backpropate the gradient to the parameters
    # first backprop into parameters W2 and b2
    dW2 = np.dot(hidden_layer.T, dscores)
    db2 = np.sum(dscores, axis=0, keepdims=True)
    # next backprop into hidden layer
    dhidden = np.dot(dscores, W2.T)
    # backprop the ReLU non-linearity
    dhidden[hidden_layer <= 0] = 0
    # finally into W,b
    dW = np.dot(X.T, dhidden)
    db = np.sum(dhidden, axis=0, keepdims=True)

    # add regularization gradient contribution
    dW2 += reg * W2
    dW += reg * W

    # perform a parameter update
    W = W - (step_size * dW)
    b = b - (step_size * db)
    W2 = W2 - (step_size * dW2)
    b2 = b2 - (step_size * db2)


i: 0
iteration: 0 loss:  32.5811559677
i: 1
i: 2
i: 3
i: 4


FloatingPointError: overflow encountered in exp

In [15]:
scores

array([[ 1019.96838784,  1017.62812345,  1020.19010631, ...,
         1017.79983993,    -2.13902841,    -1.51737584],
       [ 1029.22418603,  1026.86437657,  1029.4460778 , ...,
         1027.03715127,    -2.15720067,    -1.52896707],
       [ 1018.49228396,  1016.15929058,  1018.71576867, ...,
         1016.3297352 ,    -2.13491693,    -1.51437273],
       ..., 
       [ 1001.89645105,   999.59930425,  1002.11503256, ...,
          999.76676324,    -2.10129292,    -1.49146681],
       [ 1051.75552051,  1049.34126484,  1051.98350284, ...,
         1049.52088271,    -2.20319834,    -1.56245528],
       [ 1091.32085339,  1088.8170872 ,  1091.5605351 , ...,
         1089.00623604,    -2.28278227,    -1.61894958]])

In [21]:
np.exp(100)

2.6881171418161356e+43

In [39]:
print(X_train)

[[ 0.22  0.62 -0.02 ...,  0.15  0.36  0.18]
 [-0.01 -0.15  0.11 ...,  0.36  0.36 -0.14]
 [-0.01 -0.02  0.11 ..., -0.27  0.25 -0.14]
 ..., 
 [-0.01  0.24 -0.15 ..., -0.06  0.36  0.18]
 [ 0.1   0.36  0.24 ..., -0.27  0.36  0.35]
 [ 0.22  0.36 -0.02 ...,  0.15  0.04 -0.14]]


In [45]:
np.dot(np.dot(X_train, W), W2)

array([[  4.31884240e-04,  -6.58404366e-04,   1.31197886e-03, ...,
          4.51130063e-05,  -4.25498956e-04,   5.26483825e-05],
       [  3.83254805e-05,  -7.04059758e-04,  -3.18262525e-05, ...,
         -1.76491048e-05,  -1.37133311e-04,   2.94302159e-04],
       [ -3.36575085e-04,   3.07283677e-04,  -3.75869643e-04, ...,
         -1.93578635e-04,   3.12090417e-04,   2.30162677e-04],
       ..., 
       [ -1.26300996e-04,  -1.25848545e-03,   3.15959156e-04, ...,
          2.75332498e-05,   4.32456422e-04,  -7.18736077e-04],
       [ -8.00550152e-05,  -2.66919190e-04,   5.40987105e-04, ...,
         -4.82480956e-04,   5.33839388e-04,  -6.11393212e-04],
       [  8.40877814e-06,  -2.97410346e-04,   5.73251642e-04, ...,
         -9.10491108e-06,  -2.07307414e-04,   2.62519900e-04]])

In [41]:
b

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.]])