In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import *
from sklearn import cross_validation
from sklearn.preprocessing import MinMaxScaler

/anaconda/anaconda/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
data = read_csv("/Users/mrigank/Desktop/python_projects/ML_project/letter-recognition.data.csv", sep=',', header=None)
data

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0      T   2   8   3   5   1   8  13   0   6   6  10   8   0   8   0   8
1      I   5  12   3   7   2  10   5   5   4  13   3   9   2   8   4  10
2      D   4  11   6   8   6  10   6   2   6  10   3   7   3   7   3   9
3      N   7  11   6   6   3   5   9   4   6   4   4  10   6  10   2   8
4      G   2   1   3   1   1   8   6   6   6   6   5   9   1   7   5  10
5      S   4  11   5   8   3   8   8   6   9   5   6   6   0   8   9   7
6      B   4   2   5   4   4   8   7   6   6   7   6   6   2   8   7  10
7      A   1   1   3   2   1   8   2   2   2   8   2   8   1   6   2   7
8      J   2   2   4   4   2  10   6   2   6  12   4   8   1   6   1   7
9      M  11  15  13   9   7  13   2   6   2  12   1   9   8   1   1   8
10     X   3   9   5   7   4   8   7   3   8   5   6   8   2   8   6   7
11     O   6  13   4   7   4   6   7   6   3  10   7   9   5   9   5   8
12     G   4   9   6   7   6   7   8   6   2   6   5  11   4   8   7   8
13     M   6   9   8   6   9   7   8   6   5   7   5   8   8   9   8   6
14     R   5   9   5   7   6   6  11   7   3   7   3   9   2   7   5  11
15     F   6   9   5   4   3  10   6   3   5  10   5   7   3   9   6   9
16     O   3   4   4   3   2   8   7   7   5   7   6   8   2   8   3   8
17     C   7  10   5   5   2   6   8   6   8  11   7  11   2   8   5   9
18     T   6  11   6   8   5   6  11   5   6  11   9   4   3  12   2   4
19     J   2   2   3   3   1  10   6   3   6  12   4   9   0   7   1   7
20     J   1   3   2   2   1   8   8   2   5  14   5   8   0   7   0   7
21     H   4   5   5   4   4   7   7   6   6   7   6   8   3   8   3   8
22     S   3   2   3   3   2   8   8   7   5   7   5   7   2   8   9   8
23     O   6  11   7   8   5   7   6   9   6   7   5   9   4   8   5   5
24     J   3   6   4   4   2   6   6   4   4  14   8  12   1   6   1   6
25     C   6  11   7   8   3   7   8   7  11   4   7  14   1   7   4   8
26     M   7  11  11   8   9   3   8   4   5  10  11  10  10   9   5   7
27     W  12  14  12   8   5   9  10   4   3   5  10   7  10  12   2   6
28     H   6   9   8   7   6   8   6   6   7   7   7   9   6   8   4   8
29     G   3   6   4   4   2   6   6   5   5   6   6   9   2   8   4   8
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
19970  F   7  10   9   8   7   9   7   2   6  12   4   6   5   9   4   9
19971  C   5  10   7   9   8   5   6   4   4   7   6  11   5  11   8  10
19972  V   4   7   6   5   6   8   6   4   2   7   8   8   7   9   4   6
19973  T   4   4   5   3   2   5  12   2   8  11   9   4   0  10   2   4
19974  N   5   9   5   4   2   9  11   5   3   5   6   9   5  11   2   6
19975  E   1   0   1   0   0   5   8   5   7   7   6  12   0   8   6  10
19976  L   3   8   3   6   2   0   2   4   6   1   0   8   0   8   0   8
19977  A   3   9   5   6   2   6   5   3   1   6   1   8   2   7   2   7
19978  K   5  11   5   8   5   3   8   7   3   6   4  11   3   8   2  11
19979  M   6   9  10   7  12   7   5   3   2   7   5   8  15   7   4   6
19980  R   2   3   3   2   2   7   7   5   5   7   5   6   2   7   4   8
19981  S   6  12   6   7   3   6   8   3   6  13   7   7   2   9   3   7
19982  Y   3   9   5   6   3   7   9   1   6   6  11   8   2  11   2   7
19983  V   7  10   5   5   2   6  11   5   4  11   9   4   4  11   3  10
19984  S   2   0   2   1   1   8   7   4   6   5   6   8   0   8   7   8
19985  M   5   6   8   4   5   9   6   2   4   9   5   7   8   6   2   8
19986  O   9  15   6   8   5   5   7   7   4  10   7  10   5   9   5   8
19987  L   3   7   3   5   1   0   1   6   6   0   0   6   0   8   0   8
19988  D   6   9   8   8   8   7   6   5   7   7   5   9   6   5  10   3
19989  P   2   1   3   2   1   4  10   3   5  10   8   5   0   9   3   7
19990  W   3   8   5   6   5  11  11   2   2   5   8   7   7  12   1   7
19991  O   4   3   5   4   2   7   6   8   8   6   5   7   3   8   4   8
19992  E   4   9   5   6   3   5   9   2  10  10   8   9   2   8

In [3]:
data = np.array(data, dtype=object)

In [15]:
# seperate out X and y
X = data[:,1:]
y = data[:,0:1]
print("size of X is:", X.shape, "size of y is:", y.shape)
# insert the 1's to X
## adding biases to original X
#X = np.insert(X,0,1,axis=1)
# X = np.concatenate((np.ones(shape = (X.shape[0],1)),X),axis=1)
#print("size of X is:", X.shape, "size of y is:", y.shape)

size of X is: (20000, 16) size of y is: (20000, 1)


In [16]:
X

array([[-2.02355, 0.9645000000000001, -2.1218500000000002, ...,
        -0.33885000000000076, -3.69175, 0.1988000000000003],
       [0.9764499999999998, 4.9645, -2.1218500000000002, ...,
        -0.33885000000000076, 0.30825000000000014, 2.1988000000000003],
       [-0.023550000000000182, 3.9645, 0.8781499999999998, ...,
        -1.3388500000000008, -0.6917499999999999, 1.1988000000000003],
       ..., 
       [1.9764499999999998, 1.9645000000000001, 0.8781499999999998, ...,
        3.6611499999999992, -1.6917499999999999, -3.8011999999999997],
       [-2.02355, -4.0355, -1.1218500000000002, ..., 0.6611499999999992,
        1.3082500000000001, 0.1988000000000003],
       [-0.023550000000000182, 1.9645000000000001, 0.8781499999999998, ...,
        -1.3388500000000008, -1.6917499999999999, 0.1988000000000003]], dtype=object)

In [17]:
#scaler = MinMaxScaler(feature_range=(0, 1))
#X = scaler.fit_transform(X)
X -= np.mean(X, axis = 0) # zero-center the data (important)
#X /= np.std(X, axis = 0)
cov = np.dot(X.T, X) / X.shape[0] # get the data covariance matrix
X.shape

(20000, 16)

In [18]:
y

array([['T'],
       ['I'],
       ['D'],
       ..., 
       ['T'],
       ['S'],
       ['A']], dtype=object)

In [19]:
## y labels are formatted into a array of 26 binary numbers, for 26 different classes
y_new = np.zeros(shape = (y.shape[0],26))
y_new
#y_train.append(temp)
u = np.unique(y)
for i in range(len(y)):
    for j in range(len(y_new[0])):
        if (y[i] == u[j]):
            y_new[i,j]=1
            break

In [20]:
y_new[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
y_new.shape

(20000, 26)

In [22]:
# 25% of the data is kept apart for cross-validation and testing
## sklearn function is used to do so
X_train, X_t_cv, y_train, y_t_cv = cross_validation.train_test_split(X, y_new, test_size=0.25)
# data seperated for test & cross-validation
X_cv, X_test, y_cv, y_test = cross_validation.train_test_split(X_t_cv, y_t_cv, test_size=0.5)
X_train.shape, y_train.shape
# train: 15000 : cv: 2500 : test: 2500 observations

((15000, 16), (15000, 26))

In [23]:
y_train[0]

array([ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [24]:
X_train = X_train[0:100,:]
X_train.shape

(100, 16)

In [25]:
y_train = y_train[0:100,:]
y_train.shape

(100, 26)

In [26]:
def sigmoid (X):
    return 1/(1 + np.exp(-np.float32(X)))

def sigmoidPrime (X):
    a = sigmoid(X)
    return a * (1-a)

In [27]:
def forward(X, W1, W2, y):
    Lambda = 0.001
    a1 = X
    z2 = np.dot(X, W1)# + self.b1
    a2 = sigmoid(z2)
    z3 = np.dot(a2, W2)# + self.b2
    
    yHat = sigmoid(z3)
    
    #J = np.sum((y_train * np.log(yHat)) + ((1-y_train) * np.log(1-yHat)))
    J = 0.5*np.sum((y-yHat)**2)/X.shape[0] + (Lambda/2)*(np.sum(W1**2)+np.sum(W2**2))
    return yHat, J

In [28]:
def costFunction (y_train, yHat):
    #J = np.sum((y_train * np.log(yHat)) + ((1-y_train) * np.log(1-yHat)))
    #J = 0.5 * np.sum((yHat - y_train)**2)
    J = 0.5*sum((y-self.yHat)**2)/X.shape[0] + (Lambda/2)*(sum(W1**2)+sum(W2**2))
    return J

In [29]:
def backPropagation (X, W1, W2, y):
    
    a1 = X
    z2 = np.dot(X, W1)# + self.b1
    a2 = sigmoid(z2)
    z3 = np.dot(a2, W2)# + self.b2
    yHat = sigmoid(z3)
    
    delta3 = np.multiply((yHat - y_train), sigmoidPrime(z3))
    delta2 = np.dot(delta3, W2.T) * sigmoidPrime(z2)
    
    dJdW2 = np.dot(a2.T, delta3)
    dJdW1 = np.dot(a1.T, delta2)
    
    # unrolling Weight matrices into a single vector
    #Dvec = np.append(dJdW1.ravel(),dJdW2.ravel(), axis=0)
    
    return dJdW1, dJdW2#, Dvec

In [38]:
n_in = 16
n_hidden = 32
n_out = 26
alpha = 0.1
epsilon = 0.00001
Lambda = 0.001
mu = 0.9
v1=0
v2=0

np.random.seed(1)
W1 = 0.01 * np.random.randn(n_in, n_hidden)
W2 = 0.01 * np.random.randn(n_hidden, n_out)
#Wvec = np.append(W1.ravel(), W2.ravel(), axis=0)

In [39]:
W1.shape

(16, 32)

In [44]:
W1_new = W1
W2_new = W2

In [45]:
# training the network


#J = []
for epoch in range(2):
    yHat, J = forward(X_train, W1, W2, y_train)
    print("yHat: \n", yHat[1])
    #J.append(costFunction(y_train, yHat, X_train.shape[0]))
    #J = costFunction(y_train, yHat)
    #if (epoch % 10000 == 0):
     #   print("Cost is: ", J)
    # Momentum update
    dJdW1, dJdW2 = backPropagation(X_train, W1_new, W2_new, y_train)
    print("dW1: \n", dJdW1[0])
    print("dW2: \n", dJdW2[0])
    #v2 = mu * v2 - alpha * dJdW2 # integrate velocity
    #v1 = mu * v1 - alpha * dJdW1
    #x += v # integrate position
    W2_new = W2_new - alpha * dJdW2 #W2_new = W2_new - v2
    W1_new = W1_new - alpha * dJdW1 #W1_new = W1_new - v1
    print("epoch value is:", epoch, "cost is:", J)

yHat: 
 [ 0.49705333  0.49865916  0.5117951   0.50572407  0.49863327  0.49965531
  0.49835357  0.50464201  0.50332403  0.5121882   0.49896136  0.50853664
  0.49861199  0.49029854  0.50511211  0.50316882  0.50515085  0.50231123
  0.49474445  0.49688008  0.50276291  0.5043565   0.50267857  0.49604025
  0.50228858  0.50106198]
dW1: 
 [0.0032019551888154045 -0.016477722989008743 -0.015035837883060177
 -0.005898785284027613 0.014706414395707022 0.009903310424366533
 0.013018911682925589 0.022864542144378462 0.02331932428149707
 0.024003602270660722 -0.010454411101456125 -0.015975712000721475
 0.009156535357741148 -0.023846436855820295 0.005707989122884629
 0.020400169127056535 0.006014900772465666 0.037698426215795486
 -0.0034363090977478266 0.022218600153249717 -0.017082835818328767
 -0.007484127490170068 0.01586000251229123 -0.01109180583318487
 -0.029305068958594825 0.021102734453589223 -0.03174947342503883
 0.00021476044448650417 -0.019238255494704794 -0.014254634036007127
 0.0014110142

In [89]:
# preparing numerical gradient 1

numGrad1 = np.zeros(np.shape(W1))
epsilon_ary1 = np.zeros(np.shape(W1))

for i in range(W1.shape[0]):
    for j in range(W1.shape[1]):
        epsilon_ary1[i,j] = epsilon
        #a1, z2, a2, z3, yHat = forward(X_train, W1-epsilo_ary1, W2)
        cost1 = costFunction(y_train,
                             forward(X_train, W1-epsilon_ary1, W2))
        cost2 = costFunction(y_train,
                             forward(X_train, W1+epsilon_ary1, W2))
        numGrad1[i,j] = (cost2 - cost1) / (2*epsilon)
        epsilon_ary1[i,j] = 0

In [90]:
# preparing numerical gradient 2

numGrad2 = np.zeros(np.shape(W2))
epsilon_ary2 = np.zeros(np.shape(W2))

for i in range(W2.shape[0]):
    for j in range(W2.shape[1]):
        epsilon_ary2[i,j] = epsilon
        #a1, z2, a2, z3, yHat = forward(X_train, W1-epsilo_ary1, W2)
        cost1 = costFunction(y_train,
                             forward(X_train, W1, W2-epsilon_ary2))
        cost2 = costFunction(y_train,
                             forward(X_train, W1, W2+epsilon_ary2))
        numGrad2[i,j] = (cost2 - cost1) / (2*epsilon)
        epsilon_ary2[i,j] = 0

In [91]:
# gradient checking
## relative error

numGrad = np.hstack((numGrad1.flatten(),
                     numGrad2.flatten()
                    ))
dJdW1, dJdW2 = backPropagation(X_train, W1, W2, y_train)
grad = np.hstack((dJdW1.flatten(),
                  dJdW2.flatten()
                 ))
norm1 = np.linalg.norm(numGrad - grad)
norm2 = np.linalg.norm(numGrad)
norm3 = np.linalg.norm(grad)

relative_error = norm1 / (norm2 + norm3)

In [92]:
relative_error

0.99778706437275244

In [44]:
numGrad2[0,0], dJdW2[0,0]



(-2542.0501828193665, 594.33641732139108)

In [45]:
numGrad1[0,0], dJdW1[0,0]




(-1338.1205499172211, 303.17580931613264)

In [20]:
W1_new

array([[  1.85772259e+00,   6.16641776e+00,  -4.43116402e-01,
         -1.44746776e+00,  -5.48975446e-01,   1.01952820e+00,
          1.23567724e+00,   8.68147493e+00,  -5.19214753e+00,
         -9.17030410e-01,   3.83805931e+00,  -8.07007769e-01,
         -3.44972187e+00,   8.43571224e-01,   3.97219458e+00,
         -8.67999588e+00,  -5.20622483e+00,  -3.22243168e+00,
          1.06041079e+00,  -1.84367069e+00,  -5.89744346e+00,
         -3.28665450e-01,  -3.18090918e+00,   5.24337837e+00,
         -5.80214604e-01,   3.32372959e-01,   7.93117399e-01,
          1.20893194e+00,   4.14839909e-01,   1.77534772e+00,
         -4.43610626e+00,  -1.94177636e+00],
       [ -4.64433639e-01,  -1.83517165e+00,   4.51038761e+00,
          1.41893070e+00,  -1.09567169e+00,  -2.87908424e+00,
         -1.09345094e+00,   2.42062477e+00,  -2.54190522e+00,
         -1.81323125e+00,   2.01463977e+00,  -1.77922402e+00,
          1.35543034e+00,  -2.92498113e+00,   4.18712353e+00,
         -1.83114462e+00,

In [21]:
W1

array([[  4.87303609e-01,  -1.83526924e-01,  -1.58451526e-01,
         -3.21890587e-01,   2.59622289e-01,  -6.90461609e-01,
          5.23443529e-01,  -2.28362070e-01,   9.57117288e-02,
         -7.48111126e-02,   4.38632381e-01,  -6.18042213e-01,
         -9.67251612e-02,  -1.15216306e-01,   3.40130833e-01,
         -3.29967380e-01,  -5.17284623e-02,  -2.63357525e-01,
          1.26641240e-02,   1.74844564e-01,  -3.30185753e-01,
          3.43417113e-01,   2.70477216e-01,   1.50748302e-01,
          2.70256785e-01,  -2.05118358e-01,  -3.68670677e-02,
         -2.80730830e-01,  -8.03664239e-02,   1.59106640e-01,
         -2.07498226e-01,  -1.19026058e-01],
       [ -2.06151810e-01,  -2.53561692e-01,  -2.01373839e-01,
         -3.79937968e-03,  -3.35193105e-01,   7.03247093e-02,
          4.97940653e-01,   2.22613248e-01,  -5.75506657e-02,
         -2.66288689e-01,  -2.24147488e-01,   5.07736380e-01,
          1.52423264e-02,  -1.91098694e-01,   5.72746454e-02,
          6.30076541e-01,